### ISSUE TITLE
UI tesztek készítése.

### ISSUE THREAD

**Issue by klenium** [klenium/tetris#7]
Javaslat: Selenium, Sikuli, Appium

**Comment by klenium** [comment]
A 3 javaslat közül a Sikuli lehet alkalmas A JavaFX-es projektben lévő canvas tartalmának tesztelésére.

Azonban a JavaFX rendszerekhez vannak külön kifejlesztett tesztkörnyezetek is, pl. [TestFX][1].

[1]: https://github.com/TestFX/TestFX

**Comment by klenium** [comment]
A Sikuli csak headed típusú gépen tud futni, tehát szükséges hozzá egy bekapcsolt monitor. Ilyen tesztelés fölösleges lenne, mert ha már a saját gépemen futtatom a programot, az integrációs tesztnél és a program kipróbálásánál úgyis látható, mi jelenik meg. Ha headless szerveren nem fut, a legfontosabb folytonos automatizálást elvesztjük.

A TestFX elvileg tud headless tesztelést biztosítani, viszont nincs API-ja külön `Canvas` kezelésére, de az megoldható plusz algoritmusokkal. Kipróbálom, mennyire alkalmas automatizálásra egy új tesztprojektben.

**Comment by klenium** [comment]
Én ezt feladom, túl sok idő ment már el rá, és nem sikerül beüzemelni Travis-on a projektben a TestFX használatát. A lokális tesztek beüzemelésénél is volt pár probléma (a canvas-ból se egyszerű kinyerni a pixeladatokat), de ott végső soron működött, és egy [egyszerű külső tesztprojektet][1] Travis-on is [sikerült összekötni][2] a TestFX rendszerrel. De ennél a Tetris projektnél [rengeteg hibát dob][3], ha Travis-on futnak a tesztek, valami gond van az időzítőkkel, a hiba a Monocle rendszerben lehet (legalábbis nem találok más leírást arról, hogy nekem kellene máshogy csinálni).
```
java.lang.AbstractMethodError: Receiver class com.sun.glass.ui.monocle.MonocleTimer does not define or inherit an implementation of the resolved method abstract _pause(J)V of abstract class com.sun.glass.ui.Timer.
	at com.sun.glass.ui.Timer.pause(Timer.java:143)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pauseTimer(QuantumToolkit.java:501)
	at com.sun.javafx.tk.quantum.QuantumToolkit.postPulse(QuantumToolkit.java:488)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$12(QuantumToolkit.java:344)
	at com.sun.glass.ui.monocle.MonocleTimer$1.run(MonocleTimer.java:58)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

Ha meg már nem tudom a Travis-on automatizálni a GUI tesztelést, maradna a saját gépen futtatás, de annak kevés haszna van, lásd a Sikuli-ről írtakat. Esetleg fel lehetne húzni egy réteget a JavaFX és a játék megjelenítési logikája közé, hogy így lehessen tesztelni,  de ennél fontosabb a többi hiba javítása, a megjelenítésről majd teljes integrációs teszt gondoskodik.

[1]: https://github.com/klenium/jfxtest
[2]: https://travis-ci.org/klenium/jfxtest/builds/519438169#L661
[3]: https://travis-ci.org/klenium/tetris/builds/519482980

**Comment by klenium** [comment]
A részfeladat lezárva, [összefoglaló a Wikin][1].

[1]: https://github.com/klenium/tetris/wiki/2.2.-UI-tesztek-k%C3%A9sz%C3%ADt%C3%A9se

**Comment by klenium** [comment]
Érdekes, hogy a tesztprojekt mégis működik. Ebben a projektben próbálkoztam a `Platform.runLater`, `Timer` eltávolításával, egyik se oldotta meg. Egyedül még az időzítő tesztjeinél vannak időfüggő metódusok hívva, a `Thread.sleep`. Máshol a projektben nincs időkezelés, csakúgy, mint a tesztprojektnél. A `Thread.sleep` eltávolítását még nem próbáltam, talán az a hiba?

**Comment by klenium** [comment]
Hát ez marhajó, semmi gond nincs az időzítők használatával, [le tudtam futtatni][1] most a GUI teszteket. Kicsit más most az Application felépítése, lehet valamit ott rontottam el, de összességében hasonló, nem értem mi volt a baj tegnap. Esetleg a JDK és Maven csomagok verziói voltak [inkompatibilisek][2].

[1]: https://travis-ci.org/klenium/tetris/builds/519610470#L548
[2]: https://github.com/klenium/tetris/commit/d82cbd015f5cc06898ad55913c2a6b26dbc3aeb7#diff-61657881d138c2b7ac1366d88c9ee035

**Comment by klenium** [comment]
A következőket lehet érdemes tesztelni a GUI-n:

- [x] A gomblenyomásra megkapja-e a játék a megfelelő parancsot?
- [x] Nem használt gomblenyomással kap-e valamilyen parancsot a játék?

Ezek a tesztek a aa072fe commit-ban lettek felvéve.

- [x] A tetrominó canvas-a üres-e mindenhol magát a formát kivéve?
- [x] A tetrominó formájának helyén a megfelelő színnel van-e kitöltve a canvas?
- [x] Ha mozgatjuk a tetrominót, a régi pozíció üres, és az új kiszínezett lesz-e?

Ezek a tesztek a 835713b commit-ban lettek felvéve.

- [x] Ha csak a tetrominót mozgatjuk, a játéktábla canvas-a változatlan marad-e?
- [x] Ha a tetrominó leér, változik-e a játékpálya képe?
- [x] Ha egy teljes sort törlünk, a régi pozíciókban üresre vagy a fölötte lévő színére változik-e a játéktábla képe?

Ezek a tesztek a b9aad8f commit-ban lettek felvéve.

- [x] Ha a játéknak vége, törlődik-e a tetrominóhoz tartozó canvas tartalma, és megváltozik-e a játékpályáé?

Ez a teszt a ce6b202 commit-ban lett felvéve.

Ránézésre ennyi teszt lefedik a `Main`, `GraphicGameFrame`, és `MainApplication` osztályokat is, amik az egységteszteknél le voltak tiltva.

Hatékonyságnövelés érdekében érdemes `TestUtil` osztályt bővíteni. Kétféle ellenőrzési mód lesz: a teljes kirajzolt kép minden pixelét végigvizsgálja, és a másik, ahol csak változásokat vagy pár mintavételi pontot néz.

**Comment by klenium** [comment]
A játéktáblához sikerült 3 tesztet beüzemelni. Közben a SonarQube talált pár helytelen kódrészletet.

**Comment by klenium** [comment]
Mindegyik GUI teszt elkészült, és lefutnak Travis-on. Egy kis kódszépítgetés majd még nem árt.

[Leszedhető][1] most már a tiltás a kódlefedettség mérésnél a nézet osztályairól. Az új lefedettség 95.8%.

A Wiki oldalt módosítottam a változásoknak megfelelően.

[1]: https://github.com/klenium/tetris/commit/7c18cfab926ee8b43d6097826ace7aa3c11c37e3
